[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "lineless-table-rec>=0.1.0",
    "rapidocr-onnxruntime>=1.4.4",
    "wired-table-rec>=1.2.0",
]
